# GENERATED FILE - do not edit. Source: contract/contract.json (core 2cc44c16f516).
# Regenerate with: python scripts/codegen.py

"""Every merchant-facing route the core declares, keyed as its conformance table keys it."""

from __future__ import annotations

from typing import Mapping

from .types import RouteSpec

ROUTES: Mapping[str, RouteSpec] = {
    "POST /v1/api-allowlist/add": RouteSpec(
        method="POST",
        path="/v1/api-allowlist/add",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind="plain",
    ),
    "POST /v1/api-allowlist/enable": RouteSpec(
        method="POST",
        path="/v1/api-allowlist/enable",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind="plain",
    ),
    "POST /v1/api-allowlist/list": RouteSpec(
        method="POST",
        path="/v1/api-allowlist/list",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind="plain",
    ),
    "POST /v1/api-allowlist/remove": RouteSpec(
        method="POST",
        path="/v1/api-allowlist/remove",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind="plain",
    ),
    "POST /v1/auto-withdraw/delete": RouteSpec(
        method="POST",
        path="/v1/auto-withdraw/delete",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/auto-withdraw/list": RouteSpec(
        method="POST",
        path="/v1/auto-withdraw/list",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind="plain",
    ),
    "POST /v1/auto-withdraw/set": RouteSpec(
        method="POST",
        path="/v1/auto-withdraw/set",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/balance": RouteSpec(
        method="POST",
        path="/v1/balance",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/batch/info": RouteSpec(
        method="POST",
        path="/v1/batch/info",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "GET /v1/claim/{token}": RouteSpec(
        method="GET",
        path="/v1/claim/{token}",
        auth="public",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/claim/{token}": RouteSpec(
        method="POST",
        path="/v1/claim/{token}",
        auth="public",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "GET /v1/currencies": RouteSpec(
        method="GET",
        path="/v1/currencies",
        auth="public",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "GET /v1/documents/balance": RouteSpec(
        method="GET",
        path="/v1/documents/balance",
        auth="key",
        idempotent=False,
        safe=True,
        bare=True,
        list_kind=None,
    ),
    "GET /v1/documents/batch": RouteSpec(
        method="GET",
        path="/v1/documents/batch",
        auth="key",
        idempotent=False,
        safe=True,
        bare=True,
        list_kind=None,
    ),
    "GET /v1/documents/fees": RouteSpec(
        method="GET",
        path="/v1/documents/fees",
        auth="key",
        idempotent=False,
        safe=True,
        bare=True,
        list_kind=None,
    ),
    "POST /v1/documents/jobs": RouteSpec(
        method="POST",
        path="/v1/documents/jobs",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "GET /v1/documents/jobs/file": RouteSpec(
        method="GET",
        path="/v1/documents/jobs/file",
        auth="key",
        idempotent=False,
        safe=True,
        bare=True,
        list_kind=None,
    ),
    "POST /v1/documents/jobs/info": RouteSpec(
        method="POST",
        path="/v1/documents/jobs/info",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "GET /v1/documents/ledger": RouteSpec(
        method="GET",
        path="/v1/documents/ledger",
        auth="key",
        idempotent=False,
        safe=True,
        bare=True,
        list_kind=None,
    ),
    "GET /v1/documents/link": RouteSpec(
        method="GET",
        path="/v1/documents/link",
        auth="key",
        idempotent=False,
        safe=True,
        bare=True,
        list_kind=None,
    ),
    "GET /v1/documents/referrals": RouteSpec(
        method="GET",
        path="/v1/documents/referrals",
        auth="key",
        idempotent=False,
        safe=True,
        bare=True,
        list_kind=None,
    ),
    "GET /v1/documents/split": RouteSpec(
        method="GET",
        path="/v1/documents/split",
        auth="key",
        idempotent=False,
        safe=True,
        bare=True,
        list_kind=None,
    ),
    "GET /v1/documents/statement": RouteSpec(
        method="GET",
        path="/v1/documents/statement",
        auth="key",
        idempotent=False,
        safe=True,
        bare=True,
        list_kind=None,
    ),
    "GET /v1/documents/wallet/statement": RouteSpec(
        method="GET",
        path="/v1/documents/wallet/statement",
        auth="key",
        idempotent=False,
        safe=True,
        bare=True,
        list_kind=None,
    ),
    "GET /v1/documents/{kind}/{id}": RouteSpec(
        method="GET",
        path="/v1/documents/{kind}/{id}",
        auth="public",
        idempotent=False,
        safe=True,
        bare=True,
        list_kind=None,
    ),
    "POST /v1/exchange-rate/list": RouteSpec(
        method="POST",
        path="/v1/exchange-rate/list",
        auth="public",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind="paged",
    ),
    "GET /v1/link/{id}": RouteSpec(
        method="GET",
        path="/v1/link/{id}",
        auth="public",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/link/{id}/checkout": RouteSpec(
        method="POST",
        path="/v1/link/{id}/checkout",
        auth="public",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/merchants": RouteSpec(
        method="POST",
        path="/v1/merchants",
        auth="onboard",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/merchants/{id}/sandbox": RouteSpec(
        method="POST",
        path="/v1/merchants/{id}/sandbox",
        auth="onboard",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "GET /v1/pay/{id}": RouteSpec(
        method="GET",
        path="/v1/pay/{id}",
        auth="public",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "GET /v1/pay/{id}/qr": RouteSpec(
        method="GET",
        path="/v1/pay/{id}/qr",
        auth="public",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/pay/{id}/select": RouteSpec(
        method="POST",
        path="/v1/pay/{id}/select",
        auth="public",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment": RouteSpec(
        method="POST",
        path="/v1/payment",
        auth="key",
        idempotent=True,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/accepted/list": RouteSpec(
        method="POST",
        path="/v1/payment/accepted/list",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind="paged",
    ),
    "POST /v1/payment/accepted/set": RouteSpec(
        method="POST",
        path="/v1/payment/accepted/set",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/accuracy/get": RouteSpec(
        method="POST",
        path="/v1/payment/accuracy/get",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/accuracy/set": RouteSpec(
        method="POST",
        path="/v1/payment/accuracy/set",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/autorefund/get": RouteSpec(
        method="POST",
        path="/v1/payment/autorefund/get",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/autorefund/set": RouteSpec(
        method="POST",
        path="/v1/payment/autorefund/set",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/batch": RouteSpec(
        method="POST",
        path="/v1/payment/batch",
        auth="key",
        idempotent=True,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/cancel": RouteSpec(
        method="POST",
        path="/v1/payment/cancel",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/discount/list": RouteSpec(
        method="POST",
        path="/v1/payment/discount/list",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind="paged",
    ),
    "POST /v1/payment/discount/set": RouteSpec(
        method="POST",
        path="/v1/payment/discount/set",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/fee-config/get": RouteSpec(
        method="POST",
        path="/v1/payment/fee-config/get",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/fee-config/set": RouteSpec(
        method="POST",
        path="/v1/payment/fee-config/set",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/history": RouteSpec(
        method="POST",
        path="/v1/payment/history",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind="paged",
    ),
    "POST /v1/payment/info": RouteSpec(
        method="POST",
        path="/v1/payment/info",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/link": RouteSpec(
        method="POST",
        path="/v1/payment/link",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/link/info": RouteSpec(
        method="POST",
        path="/v1/payment/link/info",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/link/list": RouteSpec(
        method="POST",
        path="/v1/payment/link/list",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind="paged",
    ),
    "POST /v1/payment/link/toggle": RouteSpec(
        method="POST",
        path="/v1/payment/link/toggle",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/qr": RouteSpec(
        method="POST",
        path="/v1/payment/qr",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/refund": RouteSpec(
        method="POST",
        path="/v1/payment/refund",
        auth="key",
        idempotent=True,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/resend": RouteSpec(
        method="POST",
        path="/v1/payment/resend",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/resolve": RouteSpec(
        method="POST",
        path="/v1/payment/resolve",
        auth="key",
        idempotent=True,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/send-email": RouteSpec(
        method="POST",
        path="/v1/payment/send-email",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payment/services": RouteSpec(
        method="POST",
        path="/v1/payment/services",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind="paged",
    ),
    "POST /v1/payment/testing-webhook": RouteSpec(
        method="POST",
        path="/v1/payment/testing-webhook",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payout": RouteSpec(
        method="POST",
        path="/v1/payout",
        auth="key",
        idempotent=True,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payout/approve": RouteSpec(
        method="POST",
        path="/v1/payout/approve",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payout/batch": RouteSpec(
        method="POST",
        path="/v1/payout/batch",
        auth="key",
        idempotent=True,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payout/calculate": RouteSpec(
        method="POST",
        path="/v1/payout/calculate",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payout/cancel": RouteSpec(
        method="POST",
        path="/v1/payout/cancel",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payout/fee-config/get": RouteSpec(
        method="POST",
        path="/v1/payout/fee-config/get",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payout/fee-config/set": RouteSpec(
        method="POST",
        path="/v1/payout/fee-config/set",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payout/history": RouteSpec(
        method="POST",
        path="/v1/payout/history",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind="paged",
    ),
    "POST /v1/payout/info": RouteSpec(
        method="POST",
        path="/v1/payout/info",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payout/link": RouteSpec(
        method="POST",
        path="/v1/payout/link",
        auth="key",
        idempotent=True,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payout/link/batch": RouteSpec(
        method="POST",
        path="/v1/payout/link/batch",
        auth="key",
        idempotent=True,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payout/link/cancel": RouteSpec(
        method="POST",
        path="/v1/payout/link/cancel",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payout/link/cheque": RouteSpec(
        method="POST",
        path="/v1/payout/link/cheque",
        auth="key",
        idempotent=False,
        safe=False,
        bare=True,
        list_kind=None,
    ),
    "POST /v1/payout/link/info": RouteSpec(
        method="POST",
        path="/v1/payout/link/info",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payout/link/list": RouteSpec(
        method="POST",
        path="/v1/payout/link/list",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind="paged",
    ),
    "POST /v1/payout/mass": RouteSpec(
        method="POST",
        path="/v1/payout/mass",
        auth="key",
        idempotent=True,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payout/refund-fee-config/get": RouteSpec(
        method="POST",
        path="/v1/payout/refund-fee-config/get",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payout/refund-fee-config/set": RouteSpec(
        method="POST",
        path="/v1/payout/refund-fee-config/set",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/payout/services": RouteSpec(
        method="POST",
        path="/v1/payout/services",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind="paged",
    ),
    "POST /v1/payout/validate": RouteSpec(
        method="POST",
        path="/v1/payout/validate",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/referral/info": RouteSpec(
        method="POST",
        path="/v1/referral/info",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/refund/batch": RouteSpec(
        method="POST",
        path="/v1/refund/batch",
        auth="key",
        idempotent=True,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/sandbox/deposit": RouteSpec(
        method="POST",
        path="/v1/sandbox/deposit",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/sandbox/faucet": RouteSpec(
        method="POST",
        path="/v1/sandbox/faucet",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/sandbox/reset": RouteSpec(
        method="POST",
        path="/v1/sandbox/reset",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "GET /v1/sandbox/webhooks": RouteSpec(
        method="GET",
        path="/v1/sandbox/webhooks",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind="paged",
    ),
    "POST /v1/sandbox/webhooks/replay": RouteSpec(
        method="POST",
        path="/v1/sandbox/webhooks/replay",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/split/config/get": RouteSpec(
        method="POST",
        path="/v1/split/config/get",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/split/config/set": RouteSpec(
        method="POST",
        path="/v1/split/config/set",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/split/recipient/optin": RouteSpec(
        method="POST",
        path="/v1/split/recipient/optin",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/split/recipient/optin/get": RouteSpec(
        method="POST",
        path="/v1/split/recipient/optin/get",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/split/rule": RouteSpec(
        method="POST",
        path="/v1/split/rule",
        auth="key",
        idempotent=True,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/split/rule/delete": RouteSpec(
        method="POST",
        path="/v1/split/rule/delete",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/split/rule/list": RouteSpec(
        method="POST",
        path="/v1/split/rule/list",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind="paged",
    ),
    "POST /v1/test-webhook/payment": RouteSpec(
        method="POST",
        path="/v1/test-webhook/payment",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/test-webhook/payout": RouteSpec(
        method="POST",
        path="/v1/test-webhook/payout",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/test-webhook/wallet": RouteSpec(
        method="POST",
        path="/v1/test-webhook/wallet",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/transfer/batch": RouteSpec(
        method="POST",
        path="/v1/transfer/batch",
        auth="key",
        idempotent=True,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/transfer/to-personal": RouteSpec(
        method="POST",
        path="/v1/transfer/to-personal",
        auth="key",
        idempotent=True,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/transfer/to-user": RouteSpec(
        method="POST",
        path="/v1/transfer/to-user",
        auth="key",
        idempotent=True,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/vrcs": RouteSpec(
        method="POST",
        path="/v1/vrcs",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/wallet": RouteSpec(
        method="POST",
        path="/v1/wallet",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/wallet/block": RouteSpec(
        method="POST",
        path="/v1/wallet/block",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/wallet/blocked-address-refund": RouteSpec(
        method="POST",
        path="/v1/wallet/blocked-address-refund",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/wallet/qr": RouteSpec(
        method="POST",
        path="/v1/wallet/qr",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/webhooks": RouteSpec(
        method="POST",
        path="/v1/webhooks",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
    "POST /v1/webhooks/deliveries": RouteSpec(
        method="POST",
        path="/v1/webhooks/deliveries",
        auth="key",
        idempotent=False,
        safe=True,
        bare=False,
        list_kind="paged",
    ),
    "POST /v1/webhooks/rotate-secret": RouteSpec(
        method="POST",
        path="/v1/webhooks/rotate-secret",
        auth="key",
        idempotent=False,
        safe=False,
        bare=False,
        list_kind=None,
    ),
}

ROUTE_KEYS = tuple(ROUTES)
